// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	Thumbnail sql.NullString
}

type Product struct {
	ID          int64
	Name        string
	Description string
	Price       int64
	Thumbnail   string
	Inventory   int32
	SupplierID  int64
	CategoryID  int64
	CreatedAt   time.Time
}
