// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: product_crud.sql

package repository

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (name, description, price, thumbnail, inventory, supplier_id, category_id)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, name, description, price, thumbnail, inventory, supplier_id, category_id, created_at
`

type CreateProductParams struct {
	Name        string
	Description string
	Price       string
	Thumbnail   string
	Inventory   int32
	SupplierID  int64
	CategoryID  int64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Thumbnail,
		arg.Inventory,
		arg.SupplierID,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Thumbnail,
		&i.Inventory,
		&i.SupplierID,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}
